# Data management using Pandas

**Data management** is a crucial component to statistical analysis and data science work.

This notebook will show you how to import, view, undertand, and manage your data using the [Pandas](http://pandas.pydata.org) data processing library, i.e., the notebook will demonstrates how to read a dataset into Python, and obtain a basic understanding of its content.

Note that **Python** by itself is a general-purpose programming language and does not provide high-level data processing capabilities.  The **Pandas** library was developed to meet this need. **Pandas** is the most popular Python library for data manipulation, and we will use it extensively in this course. **Pandas** provides high-performance, easy-to-use data structures and data analysis tools.

The main data structure that **Pandas** works with is called a **Data Frame**. This is a two-dimensional table of data in which the rows typically
represent cases and the columns represent variables (e.g. data used in this tutorial).  Pandas also has a one-dimensional data structure called a **Series** that we will encounter when accesing a single column of a Data Frame.

Pandas has a variety of functions named `read_xxx` for reading data in different formats.  Right now we will focus on reading `csv` files, which stands for comma-separated values. However the other file formats include `excel`, `json`, and `sql`.

There are many other options to `read_csv` that are very useful.  For example, you would use the option `sep='\t'` instead of the default `sep=','` if the fields of your data file are delimited by tabs instead of commas.  See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) for the full documentation for `read_csv`.


## Acknowledgments

- The dataset used in this tutorial is from https://www.coursera.org/ from the course "Understanding and Visualizing Data with Python" by University of Michigan

# Importing libraries

In [7]:
# Import the packages that we will be using
import pandas as pd                 # For data handling

#pd.set_option('display.max_columns', 100) # Show all columns when looking at dataframe

# Importing data

In [8]:
# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/MyDrive/TC1002S/NotebooksProfessor"

else:
    # Define path del proyecto
    Ruta            = ""

Mounted at /content/drive

In [9]:
# url string that hosts our .csv file
url = Ruta + "/datasets/cartwheel/cartwheel.csv"

# Read the .csv file and store it as a pandas Data Frame
df = pd.read_csv(url)

If we want to print the information about th output object type we would simply type the following:

In [10]:
type(df)

pandas.core.frame.DataFrame

# Exploring the content of the data set

Use the `shape` method to determine the numbers of rows and columns in a data frame. This can be used to confirm that we have actually obtained the data the we are expecting.

Based on what we see below, the data set being read here has $N_r$ rows, corresponding to $N_r$ observations, and $N_c$ columns, corresponding to $N_c$ variables in this particular data file.

In [ ]:
df.shape

(52, 12)

In [ ]:
# Print the number of rows
Nrows = df.shape[0]
Nrows

52

In [ ]:
# Print the number of columns
Ncols = df.shape[1]
Ncols

12

If we want to show the entire data frame we would simply write the following:

In [12]:
df

,ID,Edad,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

As you can see, we have a 2-Dimensional object where each row is an independent observation and each coloum is a variable.

Now, use the the `head()` function to show the first 5 rows of our data frame

In [13]:
df.head()
#df.head(10)

,ID,Edad,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

Also, you can use the the `tail()` function to show the last 5 rows of our data frame

In [ ]:
df.tail()
#df.tail(3)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

The columns in a Pandas data frame have names, to see the names, use the `columns` method:

To gather more information regarding the data, we can view the column names with the following function:

In [14]:
df.columns

Index(['ID', 'Edad', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

Be aware that every variable in a Pandas data frame has a data type.  There are many different data types, but most commonly you will encounter floating point values (real numbers), integers, strings (text), and date/time values.  When Pandas reads a text/csv file, it guesses the data types based on what it sees in the first few rows of the data file.  Usually it selects an appropriate type, but occasionally it does not.  To confirm that the data types are consistent with what the variables represent, inspect the `dtypes` attribute of the data frame.

In [ ]:
df.dtypes

ID                 int64
Age              float64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup    float64
Score              int64
dtype: object

Summary statistics, which include things like the mean, min, and max of the data, can be useful to get a feel for how large some of the variables are and what variables may be the most important.

In [15]:
# Summary statistics for the quantitative variables
df.describe()

,ID,Edad,GenderGroup,GlassesGroup,Height,Wingspan,CWDistance,CompleteGroup,Score
count,52.000000,51.000000,52.000000,52.000000,51.000000,51.000000,52.000000,51.000000,52.000000
mean,26.500000,28.411765,1.500000,0.500000,68.971569,67.313725,85.576923,0.843137,7.173077
std,15.154757,5.755611,0.504878,0.504878,5.303812,5.624021,14.353173,0.367290,2.211566
min,1.000000,22.000000,1.000000,0.000000,61.500000,57.500000,63.000000,0.000000,2.000000
25%,13.750000,25.000000,1.000000,0.000000,64.500000,63.000000,72.000000,1.000000,6.000000
50%,26.500000,27.000000,1.500000,0.500000,69.000000,66.000000,85.000000,1.000000,8.000000
75%,39.250000,30.000000,2.000000,1.000000,73.000000,72.000000,96.500000,1.000000,9.000000
max,52.000000,56.000000,2.000000,1.000000,79.500000,76.000000,115.000000,1.000000,10.000000

In [18]:
# Drop observations with NaN values
df.Edad.dropna().describe()
#df.Wingspan.dropna().describe()

count    51.000000
mean     28.411765
std       5.755611
min      22.000000
25%      25.000000
50%      27.000000
75%      30.000000
max      56.000000
Name: Edad, dtype: float64

It is also possible to get statistics on the entire data frame or a column as follows

- `df.mean()` Returns the mean of all columns
- `df.corr()` Returns the correlation between columns in a data frame
- `df.count()` Returns the number of non-null values in each data frame column
- `df.max()` Returns the highest value in each column
- `df.min()` Returns the lowest value in each column
- `df.median()` Returns the median of each column
- `df.std()` Returns the standard deviation of each column

In [6]:
df.mean()

<ipython-input-6-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

ID               26.500000
Age              28.411765
GenderGroup       1.500000
GlassesGroup      0.500000
Height           68.971569
Wingspan         67.313725
CWDistance       85.576923
CompleteGroup     0.843137
Score             7.173077
dtype: float64

# How to write a data frame to a File

To save a file with your data simply use the `to_csv` attribute

In [7]:
df.to_csv('myDataFrame.csv')
#df.to_csv('myDataFrame.csv', sep='\t')

# Rename columns

To change the name of a colum use the `rename` attribute

In [19]:
df = df.rename(columns={"Age": "Edad"})

df.head()

,ID,Edad,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [20]:
df = df.rename(columns={"Edad": "Age"})

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

# Selection of colums

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent observations or samples and the columns represent variables.  One common manipulation of a data frame is to extract the data for one case or for one variable.  There are several ways to do this, as shown below.

To extract all the values for one column (variable), use one of the following alternatives.

In [24]:
a = df.Age
b = df["Age"]
c = df.loc[:, "Age"]
d = df.iloc[:, 1]

print(d)

#df[["Gender", "GenderGroup"]]

0     56.0
1     26.0
2     33.0
3     39.0
4     27.0
5     24.0
6     28.0
7     22.0
8     29.0
9     33.0
10    30.0
11    28.0
12    25.0
13    23.0
14    31.0
15    26.0
16    26.0
17    27.0
18    23.0
19    24.0
20    23.0
21    29.0
22    25.0
23    26.0
24    23.0
25    28.0
26    24.0
27    25.0
28    32.0
29    38.0
30    27.0
31    33.0
32    38.0
33    27.0
34    24.0
35    27.0
36    25.0
37    26.0
38    31.0
39    30.0
40    23.0
41    26.0
42    28.0
43    26.0
44    30.0
45    39.0
46    27.0
47    24.0
48    28.0
49    30.0
50     NaN
51    27.0
Name: Age, dtype: float64

# Slicing a data set

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent cases and the columns represent variables.  One common manipulation of a data frame is to extract the data for one observation or for one variable.  There are several ways to do this, as shown below.

Lets say we would like to splice our data frame and select only specific portions of our data.  There are three different ways of doing so.

1. .loc()
2. .iloc()
3. .ix()

We will cover the .loc() and .iloc() splicing functions.

The attibute **.loc()** uses labels/column names, in specific, it takes two single/list/range operator separated by ',', the first one indicates the rows and the second one indicates columns.

In [25]:
# Return all observations of CWDistance
df.loc[:,"CWDistance"]

# Return a subset of observations of CWDistance
df.loc[:9, "CWDistance"]

# Select all rows for multiple columns, ["Gender", "GenderGroup"]
df.loc[:,["Gender", "GenderGroup"]]

# Select multiple columns, ["Gender", "GenderGroup"]me
keep = ['Gender', 'GenderGroup']
df_gender = df[keep]

# Select few rows for multiple columns, ["CWDistance", "Height", "Wingspan"]
#df.loc[4:9, ["CWDistance", "Height", "Wingspan"]]

# Select range of rows for all columns
#df.loc[10:15,:]

The attribute **iloc()** is an integer based slicing.

In [26]:
# .
df.iloc[:, :4]

# .
df.iloc[:4, :]

# .
df.iloc[:, 3:7]

# .
df.iloc[4:8, 2:4]

# This is incorrect:
#df.iloc[1:5, ["Gender", "GenderGroup"]]

  Gender  GenderGroup
4      M            2
5      M            2
6      M            2
7      F            1

# Get unique existing values

List unique values in the one of the columns

In [5]:
# List unique values in the df['Gender'] column
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [6]:
# Lets explore df["GenderGroup] as well
df.GenderGroup.unique()

array([1, 2])

# Filter, Sort and Groupby

With **Filter** you can use different conditions to filter columns. For example, df[df[year] > 1984] would give you only the column year is greater than 1984. You can use & (and) or | (or) to add different conditions to your filtering. This is also called boolean filtering.

In [28]:
df[df["Height"] >= 70]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.0,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.0,76.0,107,Y,1.0,10
8,9,29.0,M,2,Y,1,74.0,73.0,106,N,0.0,5
14,15,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.0,72.0,115,Y,1.0,6
18,19,23.0,M,2,Y,1,70.0,69.0,64,Y,1.0,3
21,22,29.0,M,2,N,0,71.0,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.0,68.0,82,Y,1.0,4
25,26,28.0,M,2,N,0,75.0,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.4,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.0,73.0,107,Y,1.0,8
33,34,27.0,M,2,N,0,77.0,75.0,100,Y,1.0,8
38,39,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
40,41,23.0,F,1,N,0,70.4,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.5,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.5,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.0,72.0,92,Y,1.0,8
46,47,27.0,M,2,N,0,78.0,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8

With **Sort** is possible to sort values in a certain column in an ascending order using `df.sort_values("ColumnName")` or in descending order using `df.sort_values(ColumnName, ascending=False)`.

Furthermore, it’s possible to sort values by Column1Name in ascending order then Column2Name in descending order by using `df.sort_values([Column1Name,Column2Name],ascending=[True,False])`

In [ ]:
df.sort_values("Height")
#df.sort_values("Height",ascending=False)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

The attribute **Groupby** involves splitting the data into groups based on some criteria, applying a function to each group independently and combining the results into a data structure. df.groupby(col) returns a groupby object for values from one column while df.groupby([col1,col2]) returns a groupby object for values from multiple columns.

In [ ]:
df.groupby(['Gender'])

Size of each group

In [ ]:
df.groupby(['Gender']).size()

df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              26
M       2              26
dtype: int64

This output indicates that we have two types of combinations.

* Case 1: Gender = F & Gender Group = 1
* Case 2: Gender = M & GenderGroup = 2.  

This validates our initial assumption that these two fields essentially portray the same information.

# Data Cleaning: handle with missing data

Before getting started to work with your data, it's a good practice to observe it thoroughly to identify missing values and handle them accordingly.

When reading a dataset using Pandas, there is a set of values including 'NA', 'NULL', and 'NaN' that are taken by default to represent a missing value.  The full list of default missing value codes is in the '`read_csv`' documentation [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).  This document also explains how to change the way that '`read_csv`' decides whether a variable's value is missing.

Pandas has functions called `isnull` and `notnull` that can be used to identify where the missing and non-missing values are located in a data frame.  

Below we use these functions to count the number of missing and non-missing values in each variable of the datasetr.

In [21]:
df.isnull()

51

Unfortunately, our output indicates that some of our columns contain missing values so we are no able to continue on doing analysis with those colums

In [ ]:
df.notnull()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,True,True
30,True,True,True,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True,True,True,True
32,True,True,True,True,True,True,True,True,True,True,True,True
33,True,True,True,True,True,True,True,True,True,True,True,True
34,True,True,True,True,True,True,True,True,True,True,True,True
35,True,True,True,True,True,True,True,True,True,True,True,True
36,True,True,True,True,True,True,True,True,True,True,True,True
37,True,True,True,True,True,True,True,True,True,True,True,True
38,True,True,True,True,True,True,True,True,True,True,True,True
39,True,True,True,True,True,True,True,True,True,True,True,True
40,True,True,True,True,True,True,True,True,True,True,True,True
41,True,True,True,True,True,True,True,True,True,True,True,True
42,True,True,True,True,True,True,True,True,True,True,True,True
43,True,True,True,True,True,True,True,True,True,True,True,True
44,True,True,True,True,True,True,True,True,True,True,True,True
45,True,True,True,True,True,True,True,True,True,True,True,True
46,True,True,True,True,True,True,True,True,True,True,True,True
47,True,True,True,True,True,True,True,True,True,True,True,True
48,True,True,True,True,True,True,True,True,True,True,True,True
49,True,True,True,True,True,True,True,False,True,True,True,True
50,True,False,True,True,True,True,True,True,True,True,False,True
51,True,True,True,True,True,True,False,True,True,True,True,True

In [ ]:
df.isnull().sum()
df.notnull().sum()

ID               52
Age              51
Gender           52
GenderGroup      52
Glasses          52
GlassesGroup     52
Height           51
Wingspan         51
CWDistance       52
Complete         52
CompleteGroup    51
Score            52
dtype: int64

Now we use these functions to count the number of missing and non-missing values in a single variable in the dataset

In [ ]:
print( df.Height.notnull().sum() )

print( pd.isnull(df.Height).sum() )

51
1

In [ ]:
# Extract all non-missing values of one of the columns into a new variable
x = df.Age.dropna().describe()
x.describe()

count     8.000000
mean     30.645922
std      16.044470
min       5.755611
25%      24.250000
50%      27.705882
75%      35.250000
max      56.000000
Name: Age, dtype: float64

# Add and eliminate columns

In some cases it is useful to create or eiminate new columns

In [ ]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Add a new column with new data

# Create a column data
NewColumnData = df.Age/df.Age

# Insert that column in the data frame
df.insert(12, "ColumnInserted", NewColumnData, True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,ColumnInserted
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,1.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,1.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,1.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,1.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,1.0

In [ ]:
# Eliminate inserted column
df.drop("ColumnInserted", axis=1, inplace = True)
#df.drop(columns=['ColumnInserted'], inplace = True)
# Remove three columns as index base
#df.drop(df.columns[[12]], axis = 1, inplace = True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Add new column derived from existing columns

# The new column is a function of another column
df["AgeInMonths"] = df["Age"] * 12

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,AgeInMonths
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,672.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,312.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,396.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,468.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,324.0

In [ ]:
# Eliminate inserted column
df.drop("AgeInMonths", axis=1, inplace = True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Add a new column with text labels reflecting the code's meaning

df["GenderGroupNew"] = df.GenderGroup.replace({1: "Female", 2: "Male"})

# Show the first 5 rows of the created data frame
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,GenderGroupNew
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,Female
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,Female
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,Female
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,Female
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,Male

In [ ]:
# Eliminate inserted column
df.drop("GenderGroupNew", axis=1, inplace = True)
#df.drop(['GenderGroupNew'],vaxis='columns',vinplace=True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Add a new column with strata based on these cut points

# Create a column data
NewColumnData = df.Age/df.Age

# Insert that column in the data frame
df.insert(1, "ColumnStrata", NewColumnData, True)

df["ColumnStrata"] = pd.cut(df.Height, [60., 63., 66., 69., 72., 75., 78.])

# Show the first 5 rows of the created data frame
df.head()

,ID,ColumnStrata,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,"(60.0, 63.0]",56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,"(60.0, 63.0]",26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,"(63.0, 66.0]",33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,"(63.0, 66.0]",39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,"(72.0, 75.0]",27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Eliminate inserted column
df.drop("ColumnStrata", axis=1, inplace = True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
# Drop several "unused" columns
#vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
#df.drop(vars, axis=1, inplace = True)

# Add and eliminate rows

In some cases it is requiered to add new observations (rows) to the data set

In [ ]:
df.tail()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [ ]:
df.loc[len(df.index)] = [26, 24, 'F', 1, 'Y', 1, 66, 'NaN', 68, 'N', 0, 3]

df.tail()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10
52,26,24.0,F,1,Y,1,66.0,NaN,68,N,0.0,3

In [ ]:
# Eliminate inserted row
df.drop([28], inplace = True )

df.tail()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10
52,26,24.0,F,1,Y,1,66.0,NaN,68,N,0.0,3

# Cleaning your data: drop out unused columns and/or drop out rows with any missing values

In [ ]:
# Drop unused columns
#vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
#df.drop(vars, axis=1, inplace = True)

#vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
#df = df[vars]

# Drop rows with any missing values
#df = df.dropna()

# Drop unused columns and drop rows with any missing values
#vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
#df = df[vars].dropna()

df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10
52,26,24.0,F,1,Y,1,66.00,NaN,68,N,0.0,3

# Final remarks


- The understanding of your dataset is essential
    - Number of observations
    - Variables
    - Data types: numerical or categorial
    - What are my variables of interest

- There are several ways to do the same thing

- Cleaning your dataset (dropping out rows with any missing values) is a good practice

- The **Pandas** library provides fancy, high-performance, easy-to-use data structures and data analysis tools

# Activity: work with the iris dataset

Repeat this tutorial with the iris data set and respond to the following inquiries

1. Calculate the statistical summary for each quantitative variables. Explain the results
    - Identify the name of each column --> using df2.columns
     - sl (sepal lenght)
     - sw (sepal width)
     - pl (sepal lenght)
     - pw (sepal width)
     - tf (type of flower)
    - Identify the type of each column --> using dataset.dtype
     - sl (sepal lenght) --> float
     - sw (sepal width) --> float
     - pl (sepal lenght) --> float
     - pw (sepal width) --> float
     - tf (Type of flower) --> object
    - Minimum, maximum, mean, average, median, standar deviation
     - min (respectively): 4.300000	2.000000	1.000000	0.100000
     - max (respectively): 7.900000	4.400000	6.900000	2.500000
     - mean (respectively): 5.843333	3.057333	3.758000	1.199333
     - average (respectively): 5.800000	3.000000	4.350000	1.300000
     - std (respetively): 0.828066	0.435866	1.765298	0.762238
    
    
2. Are there missing data? If so, create a new dataset containing only the rows with the non-missing data

 - No they aren't, in case this happens we could create an if statement to avoid this problems (Check code below)


3. Create a new dataset containing only the petal width and length and the type of Flower
 - Check code below

4. Create a new dataset containing only the setal width and length and the type of Flower

  - Check code below

5. Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column
 - Check code below

In [ ]:
#Answer to the question number 2

if df2.sw.notnull().sum() == 0 and df2.sl.notnull().sum() and df2.pw.notnull().sum() and df2.pl.notnull().sum() == 0:
  df2
elif (df2.sw.notnull().sum() > 0):
  df2.sw.dropna()
elif (df2.sl.notnull().sum() > 0):
  df2.sl.dropna()
elif (df2.pw.notnull().sum() > 0):
  df2.pw.dropna()
elif (df2.pl.notnull().sum() > 0):
  df2.pl.dropna()

In [ ]:
#Answer to the question number 3

new_df = df2[['pw', 'pl', 'tf']]

In [ ]:
#Answer to the question number 4

new_df2 = df2[['sw', 'sl', 'tf']]

In [ ]:
#Answer to the question number 5

df2.tf.replace({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2})

new_df2_last = df2[['sl', 'sw', 'tf']]

In [24]:
#Procedures using Iris

# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/MyDrive/TC1002S/NotebooksProfessor"

else:
    # Define path del proyecto
    Ruta            = ""

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
# Import the packages that we will be using
import matplotlib.pyplot as plt
import pandas as pd

# Dataset url
url = Ruta + "/datasets/iris/iris.csv"

# Load the dataset
df2 = pd.read_csv(url)

In [4]:
df2

      sl   sw   pl   pw              tf
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [26]:
type(df2)

pandas.core.frame.DataFrame

In [27]:
df2.shape

(150, 5)

In [28]:
Nrows = df2.shape[0]
Nrows

150

In [29]:
# Print the number of columns
Ncols = df2.shape[1]
Ncols

5

In [31]:
df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [32]:
df2.tail()

      sl   sw   pl   pw              tf
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [5]:
df2.columns

Index(['sl', 'sw', 'pl', 'pw', 'tf'], dtype='object')

In [6]:
df2.dtypes

sl    float64
sw    float64
pl    float64
pw    float64
tf     object
dtype: object

In [7]:
# Summary statistics for the quantitative variables
df2.describe()

               sl          sw          pl          pw
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [37]:
# Drop observations with NaN values
df2.sl.dropna().describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sl, dtype: float64

In [39]:

df2.mean()

<ipython-input-39-4a56ca50fe8e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df2.mean()

sl    5.843333
sw    3.057333
pl    3.758000
pw    1.199333
dtype: float64

In [40]:
df2.to_csv('myDataFrame2.csv')
#df.to_csv('myDataFrame.csv', sep='\t')

In [42]:
df2 = df2.rename(columns={"sl": "Sepal Lenght"})

df2.head()

   Sepal Lenght   sw   pl   pw           tf
0           5.1  3.5  1.4  0.2  Iris-setosa
1           4.9  3.0  1.4  0.2  Iris-setosa
2           4.7  3.2  1.3  0.2  Iris-setosa
3           4.6  3.1  1.5  0.2  Iris-setosa
4           5.0  3.6  1.4  0.2  Iris-setosa

In [43]:
df2 = df2.rename(columns={"Sepal Lenght": "sl"})

df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [48]:
a = df2.sl
b = df2["sl"]
c = df2.loc[:, "sl"]
d = df2.iloc[:, 1]

print(d)

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sw, Length: 150, dtype: float64

In [52]:
# Return all observations of CWDistance
df2.loc[:,"sl"]

# Return a subset of observations of sl
df2.loc[:9, "sl"]

# Select all rows for multiple columns, ["sw", "pl"]
df2.loc[:,["sw", "pl"]]

# Select multiple columns, ["sw", "pl"]me
keep = ['sl', 'pw']
df2_sl = df2[keep]

In [53]:
# .
df2.iloc[:, :4]

# .
df2.iloc[:4, :]

# .
df2.iloc[:, 3:7]

# .
df2.iloc[4:8, 2:4]

    pl   pw
4  1.4  0.2
5  1.7  0.4
6  1.4  0.3
7  1.5  0.2

In [55]:
# List unique values in the df2['tf'] column
df2.tf.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [56]:
# Lets explore df["GenderGroup] as well
df2.sw.unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [57]:
df2[df2["sw"] >= 4]

     sl   sw   pl   pw           tf
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
32  5.2  4.1  1.5  0.1  Iris-setosa
33  5.5  4.2  1.4  0.2  Iris-setosa

In [58]:
df2.sort_values("sw")

      sl   sw   pl   pw               tf
60   5.0  2.0  3.5  1.0  Iris-versicolor
62   6.0  2.2  4.0  1.0  Iris-versicolor
119  6.0  2.2  5.0  1.5   Iris-virginica
68   6.2  2.2  4.5  1.5  Iris-versicolor
41   4.5  2.3  1.3  0.3      Iris-setosa
..   ...  ...  ...  ...              ...
16   5.4  3.9  1.3  0.4      Iris-setosa
14   5.8  4.0  1.2  0.2      Iris-setosa
32   5.2  4.1  1.5  0.1      Iris-setosa
33   5.5  4.2  1.4  0.2      Iris-setosa
15   5.7  4.4  1.5  0.4      Iris-setosa

[150 rows x 5 columns]

In [59]:
df2.groupby(['tf'])

In [61]:
df2.groupby(['tf']).size()

tf
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [62]:
df2.isnull()

        sl     sw     pl     pw     tf
0    False  False  False  False  False
1    False  False  False  False  False
2    False  False  False  False  False
3    False  False  False  False  False
4    False  False  False  False  False
..     ...    ...    ...    ...    ...
145  False  False  False  False  False
146  False  False  False  False  False
147  False  False  False  False  False
148  False  False  False  False  False
149  False  False  False  False  False

[150 rows x 5 columns]

In [63]:
df2.notnull()

       sl    sw    pl    pw    tf
0    True  True  True  True  True
1    True  True  True  True  True
2    True  True  True  True  True
3    True  True  True  True  True
4    True  True  True  True  True
..    ...   ...   ...   ...   ...
145  True  True  True  True  True
146  True  True  True  True  True
147  True  True  True  True  True
148  True  True  True  True  True
149  True  True  True  True  True

[150 rows x 5 columns]

In [65]:
df2.isnull().sum()

sl    0
sw    0
pl    0
pw    0
tf    0
dtype: int64

In [66]:
df2.notnull().sum()

sl    150
sw    150
pl    150
pw    150
tf    150
dtype: int64

In [68]:
print( df2.sw.notnull().sum() )

print( pd.isnull(df2.sw).sum() )

150
0

In [69]:
x = df2.sw.dropna().describe()
x.describe()

count      8.000000
mean      21.124150
std       52.086178
min        0.435866
25%        2.600000
50%        3.028667
75%        3.575000
max      150.000000
Name: sw, dtype: float64

In [70]:
df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [72]:
# Add a new column with new data

# Create a column data
NewColumnData2 = df2.sw/df2.sw

# Insert that column in the data frame
df2.insert(5, "ColumnInserted2", NewColumnData2, True)

df2.head()

    sl   sw   pl   pw           tf  ColumnInserted2
0  5.1  3.5  1.4  0.2  Iris-setosa              1.0
1  4.9  3.0  1.4  0.2  Iris-setosa              1.0
2  4.7  3.2  1.3  0.2  Iris-setosa              1.0
3  4.6  3.1  1.5  0.2  Iris-setosa              1.0
4  5.0  3.6  1.4  0.2  Iris-setosa              1.0

In [73]:
# Eliminate inserted column
df2.drop("ColumnInserted2", axis=1, inplace = True)
#df.drop(columns=['ColumnInserted'], inplace = True)
# Remove three columns as index base
#df.drop(df.columns[[12]], axis = 1, inplace = True)

df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [76]:
# Add new column derived from existing columns

# The new column is a function of another column
df2["sw in milimeters"] = df2["sw"] *10

df2.head()

    sl   sw   pl   pw           tf  sw in milimeters
0  5.1  3.5  1.4  0.2  Iris-setosa              35.0
1  4.9  3.0  1.4  0.2  Iris-setosa              30.0
2  4.7  3.2  1.3  0.2  Iris-setosa              32.0
3  4.6  3.1  1.5  0.2  Iris-setosa              31.0
4  5.0  3.6  1.4  0.2  Iris-setosa              36.0

In [77]:
df2.drop("sw in milimeters", axis=1, inplace = True)

df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [79]:
# Add a new column with text labels reflecting the code's meaning

df2["new names"] = df2.tf.replace({"iris-setosa": "i-s", "Iris-virginica": "i-vi", "Iris-versicolor": "i-ver"})

# Show the first 5 rows of the created data frame
df2.head()

    sl   sw   pl   pw           tf    new names
0  5.1  3.5  1.4  0.2  Iris-setosa  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa  Iris-setosa

In [80]:
# Eliminate inserted column
df2.drop("new names", axis=1, inplace = True)
#df.drop(['GenderGroupNew'],vaxis='columns',vinplace=True)

df2.head()

    sl   sw   pl   pw           tf
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [81]:
df2.tail()

      sl   sw   pl   pw              tf
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [82]:
df2.loc[len(df2.index)] = [6.4, 3.4, 5.1, 4.3, 'iris-virgica']

df2.tail()

      sl   sw   pl   pw              tf
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica
150  6.4  3.4  5.1  4.3    iris-virgica

In [83]:
df2.drop([150], inplace = True )

df2.tail()

      sl   sw   pl   pw              tf
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica