# Data management using Pandas

**Data management** is a crucial component to statistical analysis and data science work.

This notebook will show you how to import, view, undertand, and manage your data using the [Pandas](http://pandas.pydata.org) data processing library, i.e., the notebook will demonstrates how to read a dataset into Python, and obtain a basic understanding of its content.

Note that **Python** by itself is a general-purpose programming language and does not provide high-level data processing capabilities.  The **Pandas** library was developed to meet this need. **Pandas** is the most popular Python library for data manipulation, and we will use it extensively in this course. **Pandas** provides high-performance, easy-to-use data structures and data analysis tools.

The main data structure that **Pandas** works with is called a **Data Frame**. This is a two-dimensional table of data in which the rows typically
represent cases and the columns represent variables (e.g. data used in this tutorial).  Pandas also has a one-dimensional data structure called a **Series** that we will encounter when accesing a single column of a Data Frame.

Pandas has a variety of functions named `read_xxx` for reading data in different formats.  Right now we will focus on reading `csv` files, which stands for comma-separated values. However the other file formats include `excel`, `json`, and `sql`.

There are many other options to `read_csv` that are very useful.  For example, you would use the option `sep='\t'` instead of the default `sep=','` if the fields of your data file are delimited by tabs instead of commas.  See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) for the full documentation for `read_csv`.


## Acknowledgments

- The dataset used in this tutorial is from https://www.coursera.org/ from the course "Understanding and Visualizing Data with Python" by University of Michigan

# Importing libraries

In [1451]:
# Import the packages that we will be using
import pandas as pd

# Importing data

In [1452]:
# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    !pwd
    !ls
    !ls "/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/"

    # Define path del proyecto
    Ruta            = "/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/"

else:
    # Define path del proyecto
    Ruta            = ""

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content
df.csv	drive  sample_data
A1_DataLoad_Cartwheel_EMPTY.ipynb	    cartwheel.csv
A2_DataManagment_Cartwheel_EMPTY.ipynb	    D1_4Kmeans_Iris_EMPTY.ipynb
A3_DataVisualization_Cartwheel_EMPTY.ipynb  NB1_LeerDatosCartWheel.ipynb

In [1453]:
# url string that hosts our .csv file
file_path = "/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/cartwheel.csv"

# Read the .csv file and store it as a pandas Data Frame
df = pd.read_csv(file_path)

If we want to print the information about th output object type we would simply type the following: type(df)

In [1454]:
type(df)

pandas.core.frame.DataFrame

# Exploring the content of the data set

Use the `shape` method to determine the numbers of rows and columns in a data frame. This can be used to confirm that we have actually obtained the data the we are expecting.

Based on what we see below, the data set being read here has $N_r$ rows, corresponding to $N_r$ observations, and $N_c$ columns, corresponding to $N_c$ variables in this particular data file.

In [1455]:
df.shape

(52, 12)

In [1456]:
#Get number of rows
Nrows = df.shape[0]

#Print number of rows]
print("The number of rows is " + str(Nrows))

The number of rows is 52

In [1457]:
#Get number of rows
NColumns = df.shape[1]

#Print number of columns
print("The number of columns is " + str(NColumns))

The number of columns is 12

If we want to show the entire data frame we would simply write the following:

In [1458]:
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

As you can see, we have a 2-Dimensional object where each row is an independent observation and each coloum is a variable.

Now, use the the `head()` function to show the first 5 rows of our data frame

In [1459]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

Also, you can use the the `tail()` function to show the last 5 rows of our data frame

In [1460]:
df.tail()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

The columns in a Pandas data frame have names, to see the names, use the `columns` method:

To gather more information regarding the data, we can view the column names with the following function:

In [1461]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

Be aware that every variable in a Pandas data frame has a data type.  There are many different data types, but most commonly you will encounter floating point values (real numbers), integers, strings (text), and date/time values.  When Pandas reads a text/csv file, it guesses the data types based on what it sees in the first few rows of the data file.  Usually it selects an appropriate type, but occasionally it does not.  To confirm that the data types are consistent with what the variables represent, inspect the `dtypes` attribute of the data frame.

In [1462]:
df.dtypes

ID                 int64
Age              float64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup    float64
Score              int64
dtype: object

Summary statistics, which include things like the mean, min, and max of the data, can be useful to get a feel for how large some of the variables are and what variables may be the most important.

In [1463]:
# Summary statistics for the quantitative variables
df_quantitative = df[["Age","Height","Wingspan","CWDistance"]]

In [1464]:
df_quantitative.mean()

Age           28.411765
Height        68.971569
Wingspan      67.313725
CWDistance    85.576923
dtype: float64

In [1465]:
df_quantitative.corr()

                 Age    Height  Wingspan  CWDistance
Age         1.000000 -0.321105 -0.250976   -0.030501
Height     -0.321105  1.000000  0.941516    0.315947
Wingspan   -0.250976  0.941516  1.000000    0.326148
CWDistance -0.030501  0.315947  0.326148    1.000000

In [1466]:
df_quantitative.count()

Age           51
Height        51
Wingspan      51
CWDistance    52
dtype: int64

In [1467]:
df_quantitative.max()

Age            56.0
Height         79.5
Wingspan       76.0
CWDistance    115.0
dtype: float64

In [1468]:
df_quantitative.min()

Age           22.0
Height        61.5
Wingspan      57.5
CWDistance    63.0
dtype: float64

In [1469]:
df_quantitative.median()

Age           27.0
Height        69.0
Wingspan      66.0
CWDistance    85.0
dtype: float64

In [1470]:
df_quantitative.std()

Age            5.755611
Height         5.303812
Wingspan       5.624021
CWDistance    14.353173
dtype: float64

In [1471]:
#Drop observations with NaN values
df.Age.dropna().describe()

count    51.000000
mean     28.411765
std       5.755611
min      22.000000
25%      25.000000
50%      27.000000
75%      30.000000
max      56.000000
Name: Age, dtype: float64

In [1472]:
df.Wingspan.dropna().describe()

count    51.000000
mean     67.313725
std       5.624021
min      57.500000
25%      63.000000
50%      66.000000
75%      72.000000
max      76.000000
Name: Wingspan, dtype: float64

It is also possible to get statistics on the entire data frame or a column as follows

- `df.mean()` Returns the mean of all columns
- `df.corr()` Returns the correlation between columns in a data frame
- `df.count()` Returns the number of non-null values in each data frame column
- `df.max()` Returns the highest value in each column
- `df.min()` Returns the lowest value in each column
- `df.median()` Returns the median of each column
- `df.std()` Returns the standard deviation of each column

# How to write a data frame to a File

To save a file with your data simply use the `to_csv` attribute

Examples:
- df.to_csv('myDataFrame.csv')
- df.to_csv('myDataFrame.csv', sep='\t')

In [1473]:
df.to_csv('df.csv')

# Rename columns

To change the name of a colum use the `rename` attribute

Example:

df = df.rename(columns={"Age": "Edad"})

df.head()

In [1474]:
df = df.rename(columns={"Age": "Edad"})
df.head()

,ID,Edad,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1475]:
# Back to the original name
df = df.rename(columns={"Edad": "Age"})
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

# Selection of colums

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent observations or samples and the columns represent variables.  One common manipulation of a data frame is to extract the data for one case or for one variable.  There are several ways to do this, as shown below.

To extract all the values for one column (variable), use one of the following alternatives.

In [1476]:
#a = df.Age
#b = df["Age"]
#c = df.loc[:, "Age"]
#d = df.iloc[:, 1]

#print(d)

#df[["Gender", "GenderGroup"]]

In [1477]:
a = df.Age
print(a)

0     56.0
1     26.0
2     33.0
3     39.0
4     27.0
5     24.0
6     28.0
7     22.0
8     29.0
9     33.0
10    30.0
11    28.0
12    25.0
13    23.0
14    31.0
15    26.0
16    26.0
17    27.0
18    23.0
19    24.0
20    23.0
21    29.0
22    25.0
23    26.0
24    23.0
25    28.0
26    24.0
27    25.0
28    32.0
29    38.0
30    27.0
31    33.0
32    38.0
33    27.0
34    24.0
35    27.0
36    25.0
37    26.0
38    31.0
39    30.0
40    23.0
41    26.0
42    28.0
43    26.0
44    30.0
45    39.0
46    27.0
47    24.0
48    28.0
49    30.0
50     NaN
51    27.0
Name: Age, dtype: float64

In [1478]:
df[["Gender", "GenderGroup"]]

   Gender  GenderGroup
0       F            1
1       F            1
2       F            1
3       F            1
4       M            2
5       M            2
6       M            2
7       F            1
8       M            2
9       F            1
10      M            2
11      F            1
12      F            1
13      F            1
14      M            2
15      M            2
16      F            1
17      M            2
18      M            2
19      F            1
20      M            2
21      M            2
22      M            2
23      M            2
24      F            1
25      M            2
26      M            2
27      M            2
28      F            1
29      F            1
30      F            1
31      F            1
32      F            1
33      M            2
34      F            1
35      M            2
36      F            1
37      F            1
38      M            2
39      M            2
40      F            1
41      M            2
42      F            1
43      F            1
44      F            1
45      F            1
46      M            2
47      M            2
48      M            2
49      F            1
50      M            2
51      M            2

# Slicing a data set

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent cases and the columns represent variables.  One common manipulation of a data frame is to extract the data for one observation or for one variable.  There are several ways to do this, as shown below.

Lets say we would like to splice our data frame and select only specific portions of our data.  There are three different ways of doing so.

1. .loc()
2. .iloc()
3. .ix()

We will cover the .loc() and .iloc() splicing functions.

The attibute **.loc()** uses labels/column names, in specific, it takes two single/list/range operator separated by ',', the first one indicates the rows and the second one indicates columns.

In [1479]:
# Return all observations of CWDistance
df.loc[:,"CWDistance"]

# Return a subset of observations of CWDistance
df.loc[:9, "CWDistance"]

# Select all rows for multiple columns, ["Gender", "GenderGroup"]
df.loc[:,["Gender", "GenderGroup"]]

# Select multiple columns, ["Gender", "GenderGroup"]me
keep = ['Gender', 'GenderGroup']
df_gender = df[keep]

# Select few rows for multiple columns, ["CWDistance", "Height", "Wingspan"]
df.loc[4:9, ["CWDistance", "Height", "Wingspan"]]

# Select range of rows for all columns
df.loc[10:15,:]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6

The attribute **iloc()** is an integer based slicing.

In [1480]:
# .
df.iloc[:, :4]

# .
df.iloc[:4, :]

# .
df.iloc[:, 3:7]

# .
df.iloc[4:8, 2:4]

# This is incorrect:
#df.iloc[1:5, ["Gender", "GenderGroup"]]

  Gender  GenderGroup
4      M            2
5      M            2
6      M            2
7      F            1

# Get unique existing values

List unique values in the one of the columns

df.Gender.unique()

In [1481]:
# List unique values in the df['Gender'] column
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [1482]:
# Lets explore df["GenderGroup] as well
df["GenderGroup"]

0     1
1     1
2     1
3     1
4     2
5     2
6     2
7     1
8     2
9     1
10    2
11    1
12    1
13    1
14    2
15    2
16    1
17    2
18    2
19    1
20    2
21    2
22    2
23    2
24    1
25    2
26    2
27    2
28    1
29    1
30    1
31    1
32    1
33    2
34    1
35    2
36    1
37    1
38    2
39    2
40    1
41    2
42    1
43    1
44    1
45    1
46    2
47    2
48    2
49    1
50    2
51    2
Name: GenderGroup, dtype: int64

# Filter, Sort and Groupby

With **Filter** you can use different conditions to filter columns. For example, df[df[year] > 1984] would give you only the column year is greater than 1984. You can use & (and) or | (or) to add different conditions to your filtering. This is also called boolean filtering.

df[df["Height"] >= 70]

In [1483]:
df[df["Height"] >= 70]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.0,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.0,76.0,107,Y,1.0,10
8,9,29.0,M,2,Y,1,74.0,73.0,106,N,0.0,5
14,15,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.0,72.0,115,Y,1.0,6
18,19,23.0,M,2,Y,1,70.0,69.0,64,Y,1.0,3
21,22,29.0,M,2,N,0,71.0,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.0,68.0,82,Y,1.0,4
25,26,28.0,M,2,N,0,75.0,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.4,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.0,73.0,107,Y,1.0,8
33,34,27.0,M,2,N,0,77.0,75.0,100,Y,1.0,8
38,39,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
40,41,23.0,F,1,N,0,70.4,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.5,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.5,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.0,72.0,92,Y,1.0,8
46,47,27.0,M,2,N,0,78.0,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8

With **Sort** is possible to sort values in a certain column in an ascending order using `df.sort_values("ColumnName")` or in descending order using `df.sort_values(ColumnName, ascending=False)`.

Furthermore, it’s possible to sort values by Column1Name in ascending order then Column2Name in descending order by using `df.sort_values([Column1Name,Column2Name],ascending=[True,False])`


df.sort_values("Height")
#df.sort_values("Height",ascending=False)

In [1484]:
df.sort_values("Height")

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

The attribute **Groupby** involves splitting the data into groups based on some criteria, applying a function to each group independently and combining the results into a data structure. df.groupby(col) returns a groupby object for values from one column while df.groupby([col1,col2]) returns a groupby object for values from multiple columns.

df.groupby(['Gender'])

In [1485]:
df.groupby(['Gender'])

Size of each group

df.groupby(['Gender']).size()

df.groupby(['Gender','GenderGroup']).size()

In [1486]:
df.groupby(['Gender']).size()

Gender
F    26
M    26
dtype: int64

In [1487]:
df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              26
M       2              26
dtype: int64

This output indicates that we have two types of combinations.

* Case 1: Gender = F & Gender Group = 1
* Case 2: Gender = M & GenderGroup = 2.  

This validates our initial assumption that these two fields essentially portray the same information.

# Data Cleaning: handle with missing data

Before getting started to work with your data, it's a good practice to observe it thoroughly to identify missing values and handle them accordingly.

When reading a dataset using Pandas, there is a set of values including 'NA', 'NULL', and 'NaN' that are taken by default to represent a missing value.  The full list of default missing value codes is in the '`read_csv`' documentation [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).  This document also explains how to change the way that '`read_csv`' decides whether a variable's value is missing.

Pandas has functions called `isnull` and `notnull` that can be used to identify where the missing and non-missing values are located in a data frame.  

Below we use these functions to count the number of missing and non-missing values in each variable of the datasetr.

In [1488]:
df.isnull()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,True,False,False,False,False
50,False,True,False,False,False,False,False,False,False,False,True,False
51,False,False,False,False,False,False,True,False,False,False,False,False

In [1489]:
df.notnull()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,True,True
30,True,True,True,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True,True,True,True
32,True,True,True,True,True,True,True,True,True,True,True,True
33,True,True,True,True,True,True,True,True,True,True,True,True
34,True,True,True,True,True,True,True,True,True,True,True,True
35,True,True,True,True,True,True,True,True,True,True,True,True
36,True,True,True,True,True,True,True,True,True,True,True,True
37,True,True,True,True,True,True,True,True,True,True,True,True
38,True,True,True,True,True,True,True,True,True,True,True,True
39,True,True,True,True,True,True,True,True,True,True,True,True
40,True,True,True,True,True,True,True,True,True,True,True,True
41,True,True,True,True,True,True,True,True,True,True,True,True
42,True,True,True,True,True,True,True,True,True,True,True,True
43,True,True,True,True,True,True,True,True,True,True,True,True
44,True,True,True,True,True,True,True,True,True,True,True,True
45,True,True,True,True,True,True,True,True,True,True,True,True
46,True,True,True,True,True,True,True,True,True,True,True,True
47,True,True,True,True,True,True,True,True,True,True,True,True
48,True,True,True,True,True,True,True,True,True,True,True,True
49,True,True,True,True,True,True,True,False,True,True,True,True
50,True,False,True,True,True,True,True,True,True,True,False,True
51,True,True,True,True,True,True,False,True,True,True,True,True

Unfortunately, our output indicates that some of our columns contain missing values so we are no able to continue on doing analysis with those colums

In [1490]:
df.isnull().sum()
df.notnull().sum()

ID               52
Age              51
Gender           52
GenderGroup      52
Glasses          52
GlassesGroup     52
Height           51
Wingspan         51
CWDistance       52
Complete         52
CompleteGroup    51
Score            52
dtype: int64

Now we use these functions to count the number of missing and non-missing values in a single variable in the dataset

print( df.Height.notnull().sum() )

print( pd.isnull(df.Height).sum() )

In [1491]:
print( df.Height.notnull().sum() )
print( pd.isnull(df.Height).sum() )

51
1

In [1492]:
# Extract all non-missing values of one of the columns into a new variable
x = df.Age.dropna().describe()
x.describe()

count     8.000000
mean     30.645922
std      16.044470
min       5.755611
25%      24.250000
50%      27.705882
75%      35.250000
max      56.000000
Name: Age, dtype: float64

# Add and eliminate columns

In some cases it is useful to create or eiminate new columns

In [1493]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1494]:
# Add a new column with new data

# Create a column data
NewColumnData = df.Age/df.Age

# Insert that column in the data frame
df.insert(12, "ColumnInserted", NewColumnData, True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,ColumnInserted
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,1.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,1.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,1.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,1.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,1.0

In [1495]:
# # Eliminate inserted column
#df.drop("ColumnInserted", axis=1, inplace = True)
#df.drop(columns=['ColumnInserted'], inplace = True)

# # Remove three columns as index base
df.drop(df.columns[[12]], axis = 1, inplace = True)

#Print
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1496]:
# # Add new column derived from existing columns
#
# # The new column is a function of another column
df["AgeInMonths"] = df["Age"] * 12
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,AgeInMonths
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,672.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,312.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,396.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,468.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,324.0

In [1497]:
# # Eliminate inserted column
df.drop("AgeInMonths", axis=1, inplace = True)
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1498]:
# Add a new column with text labels reflecting the code's meaning

df["GenderGroupNew"] = df.GenderGroup.replace({1: "Female", 2: "Male"})

# Show the first 5 rows of the created data frame
df.head(5)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,GenderGroupNew
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,Female
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,Female
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,Female
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,Female
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,Male

In [1499]:
## Eliminate inserted column
df.drop("GenderGroupNew", axis=1, inplace = True)
##df.drop(['GenderGroupNew'],vaxis='columns',vinplace=True)

In [1500]:
## Add a new column with strata based on these cut points
#
## Create a column data
NewColumnData = df.Age/df.Age
#
## Insert that column in the data frame
df.insert(1, "ColumnStrata", NewColumnData, True)
#
df["ColumnStrata"] = pd.cut(df.Height, [60., 63., 66., 69., 72., 75., 78.])
#
## Show the first 5 rows of the created data frame
df.head()

,ID,ColumnStrata,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,"(60.0, 63.0]",56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,"(60.0, 63.0]",26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,"(63.0, 66.0]",33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,"(63.0, 66.0]",39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,"(72.0, 75.0]",27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1501]:
## Eliminate inserted column
df.drop("ColumnStrata", axis=1, inplace = True)
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [1502]:
# Drop several "unused" columns
vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
df.drop(vars, axis=1, inplace = True)

# Add and eliminate rows

In some cases it is requiered to add new observations (rows) to the data set

In [1503]:
# Print tail
df.tail()

     Age Gender Glasses  Height  Wingspan  CWDistance Complete  Score
47  24.0      M       N    79.5      75.0          82        N      8
48  28.0      M       N    77.8      76.0          99        Y      9
49  30.0      F       N    74.6       NaN          71        Y      9
50   NaN      M       N    71.0      70.0         101        Y      8
51  27.0      M       N     NaN      71.5         103        Y     10

In [1504]:
#df.loc[len(df.index)] = [26, 24, 'F', 1, 'Y', 1, 66, 'NaN', 68, 'N', 0, 3]
df.loc[len(df.index)] = [26, 'F', 'Y', 66, 'NaN', 68, 'N',10]

df.tail()

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
48  28.0      M       N    77.8     76.0          99        Y      9
49  30.0      F       N    74.6      NaN          71        Y      9
50   NaN      M       N    71.0     70.0         101        Y      8
51  27.0      M       N     NaN     71.5         103        Y     10
52  26.0      F       Y    66.0      NaN          68        N     10

In [1505]:
## Eliminate inserted row
df.drop([52], inplace = True )

df.tail()

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
47  24.0      M       N    79.5     75.0          82        N      8
48  28.0      M       N    77.8     76.0          99        Y      9
49  30.0      F       N    74.6      NaN          71        Y      9
50   NaN      M       N    71.0     70.0         101        Y      8
51  27.0      M       N     NaN     71.5         103        Y     10

# Cleaning your data: drop out unused columns and/or drop out rows with any missing values

In [1506]:
# Drop unused columns
vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
#df.drop(vars, axis=1, inplace = True)

vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars]

# Drop rows with any missing values
df = df.dropna()

# Drop unused columns and drop rows with any missing values
vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars].dropna()

df

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
0   56.0      F       Y   62.00     61.0          79        Y      7
1   26.0      F       Y   62.00     60.0          70        Y      8
2   33.0      F       Y   66.00     64.0          85        Y      7
3   39.0      F       N   64.00     63.0          87        Y     10
4   27.0      M       N   73.00     75.0          72        N      4
5   24.0      M       N   75.00     71.0          81        N      3
6   28.0      M       N   75.00     76.0         107        Y     10
7   22.0      F       N   65.00     62.0          98        Y      9
8   29.0      M       Y   74.00     73.0         106        N      5
9   33.0      F       Y   63.00     60.0          65        Y      8
10  30.0      M       Y   69.50     66.0          96        Y      6
11  28.0      F       Y   62.75     58.0          79        Y     10
12  25.0      F       Y   65.00     64.5          92        Y      6
13  23.0      F       N   61.50     57.5          66        Y      4
14  31.0      M       Y   73.00     74.0          72        Y      9
15  26.0      M       Y   71.00     72.0         115        Y      6
16  26.0      F       N   61.50     59.5          90        N     10
17  27.0      M       N   66.00     66.0          74        Y      5
18  23.0      M       Y   70.00     69.0          64        Y      3
19  24.0      F       Y   68.00     66.0          85        Y      8
20  23.0      M       Y   69.00     67.0          66        N      2
21  29.0      M       N   71.00     70.0         101        Y      8
22  25.0      M       N   70.00     68.0          82        Y      4
23  26.0      M       N   69.00     71.0          63        Y      5
24  23.0      F       Y   65.00     63.0          67        N      3
25  28.0      M       N   75.00     76.0         111        Y     10
26  24.0      M       N   78.40     71.0          92        Y      7
27  25.0      M       Y   76.00     73.0         107        Y      8
28  32.0      F       Y   63.00     60.0          75        Y      8
29  38.0      F       Y   61.50     61.0          78        Y      7
30  27.0      F       Y   62.00     60.0          72        Y      8
31  33.0      F       Y   65.30     64.0          91        Y      7
32  38.0      F       N   64.00     63.0          86        Y     10
33  27.0      M       N   77.00     75.0         100        Y      8
34  24.0      F       N   67.80     62.0          98        Y      9
35  27.0      M       N   68.00     66.0          74        Y      5
36  25.0      F       Y   65.00     64.5          92        Y      6
37  26.0      F       N   61.50     59.5          90        Y      9
38  31.0      M       Y   73.00     74.0          72        Y      9
39  30.0      M       Y   69.50     66.0          96        Y      6
40  23.0      F       N   70.40     71.0          66        Y      4
41  26.0      M       Y   73.50     72.0         115        Y      6
42  28.0      F       Y   72.50     72.0          81        Y     10
43  26.0      F       Y   72.00     72.0          92        Y      8
44  30.0      F       Y   66.00     64.0          85        Y      7
45  39.0      F       N   64.00     63.0          87        Y     10
46  27.0      M       N   78.00     75.0          72        N      7
47  24.0      M       N   79.50     75.0          82        N      8
48  28.0      M       N   77.80     76.0          99        Y      9

# Final remarks


- The understanding of your dataset is essential
    - Number of observations
    - Variables
    - Data types: numerical or categorial
    - What are my variables of interest

- There are several ways to do the same thing

- Cleaning your dataset (dropping out rows with any missing values) is a good practice

- The **Pandas** library provides fancy, high-performance, easy-to-use data structures and data analysis tools

# Activity: work with the iris dataset

Repeat this tutorial with the iris data set and respond to the following inquiries

1. Calculate the statistical summary for each quantitative variables. Explain the results
    - Identify the name of each column
    - Identify the type of each column
    - Minimum, maximum, mean, average, median, standar deviation
    
    
2. Are there missing data? If so, create a new dataset containing only the rows with the non-missing data


3. Create a new dataset containing only the petal width and length and the type of Flower


4. Create a new dataset containing only the setal width and length and the type of Flower


5. Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column

In [1507]:
# Define the col names for the iris dataset
columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']

# Dataset url
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Load the dataset
df = pd.read_csv(url, header=None, names=columns)

In [1508]:
df.shape

(150, 5)

In [1509]:
#Get number of rows
Nrows = df.shape[0]

#Print number of rows]
print("The number of rows is " + str(Nrows))

The number of rows is 150

In [1510]:
#Get number of rows
NColumns = df.shape[1]

#Print number of columns
print("The number of columns is " + str(NColumns))

The number of columns is 5

In [1511]:
df

     SepalLength  SepalWidth  PetalLength  PetalWidth         Species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [1512]:
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [1513]:
df.tail()

     SepalLength  SepalWidth  PetalLength  PetalWidth         Species
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

1. Calculate the statistical summary for each quantitative variables. Explain the results.

Identify the name of each column.
Identify the type of each column.
Minimum, maximum, mean, average, median, standar deviation.

In [1514]:
#Identify name of each column
df.columns

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species'], dtype='object')

In [1515]:
#Identify type of each column
df.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Species         object
dtype: object

In [1516]:
# Summary statistics for the quantitative variables
df_quantitative = df[["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

In [1517]:
df_quantitative.mean()

SepalLength    5.843333
SepalWidth     3.054000
PetalLength    3.758667
PetalWidth     1.198667
dtype: float64

In [1518]:
df_quantitative.corr()

             SepalLength  SepalWidth  PetalLength  PetalWidth
SepalLength     1.000000   -0.109369     0.871754    0.817954
SepalWidth     -0.109369    1.000000    -0.420516   -0.356544
PetalLength     0.871754   -0.420516     1.000000    0.962757
PetalWidth      0.817954   -0.356544     0.962757    1.000000

In [1519]:
df_quantitative.count()

SepalLength    150
SepalWidth     150
PetalLength    150
PetalWidth     150
dtype: int64

In [1520]:
df_quantitative.max()

SepalLength    7.9
SepalWidth     4.4
PetalLength    6.9
PetalWidth     2.5
dtype: float64

In [1521]:
df_quantitative.min()

SepalLength    4.3
SepalWidth     2.0
PetalLength    1.0
PetalWidth     0.1
dtype: float64

In [1522]:
df_quantitative.median()

SepalLength    5.80
SepalWidth     3.00
PetalLength    4.35
PetalWidth     1.30
dtype: float64

In [1523]:
df_quantitative.std()

SepalLength    0.828066
SepalWidth     0.433594
PetalLength    1.764420
PetalWidth     0.763161
dtype: float64

In [1524]:
#Drop observations with NaN values
df.dropna().describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

Results explanation:
1. 4 quantitative continuous variables, 1 qualitative driscrete
2. Looking at the minimum and maximum, we can see that the shortest part of the flower is the petal and the longest is the sepal.
Sepal length is the biggest value on average, sepal width and petal length have on average similar values, petal width is the smallest value on average.The values do not deviate a lot from the mean.

2. Are there missing data? If so, create a new dataset containing only the rows with the non-missing data.

In [1525]:
#No missing data
df.isnull().sum()

SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64

3. Create a new dataset containing only the petal width and length and the type of Flower

In [1526]:
df_petal = df[['PetalLength', 'PetalWidth']]
df_petal.head()

   PetalLength  PetalWidth
0          1.4         0.2
1          1.4         0.2
2          1.3         0.2
3          1.5         0.2
4          1.4         0.2

4. Create a new dataset containing only the setal width and length and the type of Flower

In [1527]:
df_sepal = df[['SepalLength', 'SepalWidth']]
df_sepal.head()

   SepalLength  SepalWidth
0          5.1         3.5
1          4.9         3.0
2          4.7         3.2
3          4.6         3.1
4          5.0         3.6

5. Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column

In [1528]:
df.columns

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species'], dtype='object')

In [1529]:
# Add a new column with text labels reflecting the code's meaning
df["CategoricalType"] = df['Species'].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2})

# Show the first 5 rows of the created data frame
df

<ipython-input-1529-d4ee81b51441>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["CategoricalType"] = df['Species'].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2})

,SepalLength,SepalWidth,PetalLength,PetalWidth,Species,CategoricalType
0,5.1,3.5,1.4,0.2,Iris-setosa,0
1,4.9,3.0,1.4,0.2,Iris-setosa,0
2,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5.0,3.6,1.4,0.2,Iris-setosa,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,2
146,6.3,2.5,5.0,1.9,Iris-virginica,2
147,6.5,3.0,5.2,2.0,Iris-virginica,2
148,6.2,3.4,5.4,2.3,Iris-virginica,2
149,5.9,3.0,5.1,1.8,Iris-virginica,2