## Leer datos
El objetivo de este notebook es leer el archivo de datos .cav con la información del dataset cartwheel.

In [30]:
#Ana Karen Zetter Márquez A01637124

#Definiciones
#rutadatos = TBD

## Import libraries

In [31]:
#Importar pakages
import pandas as pd

In [32]:
#Montar el drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [33]:
#Lista
!ls '/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/cartwheel.csv'

'/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/cartwheel.csv'

# Leer datos
Cargar el archivo de datos y ponerlo en un dataframe de Pandas

In [34]:
#Define the file path
file_path = '/content/drive/MyDrive/Profesional/Semestre 5/Análisis de datos/cartwheel.csv'

#Read the CSV file as a pandas DataFrame
df = pd.read_csv(file_path)

In [35]:
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [36]:
df.shape

(52, 12)

##Explorar datos

In [37]:
#Get number of rows
Nrows = df.shape[0]

#Print number of rows
print("The number of rows is " + str(Nrows))

The number of rows is 52

In [38]:
#Get number of columns
Ncolumns = df.shape[1]

#Print number of columns
print("The number of columns is " + str(Ncolumns))

The number of columns is 12

In [39]:
#Obtener los datos en una columna
df.Age
df["Age"]

0     56.0
1     26.0
2     33.0
3     39.0
4     27.0
5     24.0
6     28.0
7     22.0
8     29.0
9     33.0
10    30.0
11    28.0
12    25.0
13    23.0
14    31.0
15    26.0
16    26.0
17    27.0
18    23.0
19    24.0
20    23.0
21    29.0
22    25.0
23    26.0
24    23.0
25    28.0
26    24.0
27    25.0
28    32.0
29    38.0
30    27.0
31    33.0
32    38.0
33    27.0
34    24.0
35    27.0
36    25.0
37    26.0
38    31.0
39    30.0
40    23.0
41    26.0
42    28.0
43    26.0
44    30.0
45    39.0
46    27.0
47    24.0
48    28.0
49    30.0
50     NaN
51    27.0
Name: Age, dtype: float64

In [40]:
# Obtener un nuevo dataframe con algunas columnas
df2 = df[["Age","Height","Wingspan","CWDistance"]]
df2.head()

    Age  Height  Wingspan  CWDistance
0  56.0    62.0      61.0          79
1  26.0    62.0      60.0          70
2  33.0    66.0      64.0          85
3  39.0    64.0      63.0          87
4  27.0    73.0      75.0          72

In [41]:
df2.head(3)

    Age  Height  Wingspan  CWDistance
0  56.0    62.0      61.0          79
1  26.0    62.0      60.0          70
2  33.0    66.0      64.0          85

In [42]:
df2.tail(3)

     Age  Height  Wingspan  CWDistance
49  30.0    74.6       NaN          71
50   NaN    71.0      70.0         101
51  27.0     NaN      71.5         103

In [43]:
df.sort_index()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [44]:
#Ordenar por edad
df.sort_values(by='Age')

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8

In [45]:
df.iloc[[6],[7]]

   Wingspan
6      76.0

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             52 non-null     int64
 1   Age            51 non-null     float64
 2   Gender         52 non-null     object
 3   GenderGroup    52 non-null     int64
 4   Glasses        52 non-null     object
 5   GlassesGroup   52 non-null     int64
 6   Height         51 non-null     float64
 7   Wingspan       51 non-null     float64
 8   CWDistance     52 non-null     int64
 9   Complete       52 non-null     object
 10  CompleteGroup  51 non-null     float64
 11  Score          52 non-null     int64
dtypes: float64(4), int64(5), object(3)
memory usage: 5.0+ KB

In [47]:
# Identificar información faltante
df.isnull()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,True,False,False,False,False
50,False,True,False,False,False,False,False,False,False,False,True,False
51,False,False,False,False,False,False,True,False,False,False,False,False

#Estadística de las variables
Calcular e imprimir estadística

In [52]:
df.dropna().describe()

,ID,Age,GenderGroup,GlassesGroup,Height,Wingspan,CWDistance,CompleteGroup,Score
count,49.00000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,25.00000,28.408163,1.489796,0.530612,68.815306,67.173469,85.204082,0.836735,7.061224
std,14.28869,5.866282,0.505076,0.504234,5.341526,5.693153,14.249239,0.373438,2.221187
min,1.00000,22.000000,1.000000,0.000000,61.500000,57.500000,63.000000,0.000000,2.000000
25%,13.00000,25.000000,1.000000,0.000000,64.000000,63.000000,72.000000,1.000000,6.000000
50%,25.00000,27.000000,1.000000,1.000000,69.000000,66.000000,85.000000,1.000000,7.000000
75%,37.00000,30.000000,2.000000,1.000000,73.000000,72.000000,96.000000,1.000000,9.000000
max,49.00000,56.000000,2.000000,1.000000,79.500000,76.000000,115.000000,1.000000,10.000000