#Leer datos

El objetivo de este notebook es leer el archivo de datos .csv con la informaci√≥n del dataset cartwheel.

#Definiciones

In [1]:
#Aqui van las definiciones

#rutadatos = TDB

#Import libraries

In [2]:
#import pakages
import pandas as pd

In [5]:
#montar el drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
!ls "drive/MyDrive/TEC - ITC/ago - dic 2024/semanas tec/TC1002S/NotebooksProfessor/cartwheel/"

cartwheel.csv

#Leer datos

Cargar el archivo de datos y ponerlo en un dataframe de pandas

In [25]:
#Define the file path
file_path = "drive/MyDrive/TEC - ITC/ago - dic 2024/semanas tec/TC1002S/NotebooksProfessor/cartwheel/cartwheel.csv"

In [26]:
#Read the CVS file intoo a pandas DataFrame
df = pd.read_csv(file_path)

In [28]:
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [29]:
#get the number of  rows
df.shape[0]

52

In [30]:
#get the number of columns
df.shape[1]

12

In [31]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [35]:
#obtener datos de una columna
#df.age
df['Age']

0     56.0
1     26.0
2     33.0
3     39.0
4     27.0
5     24.0
6     28.0
7     22.0
8     29.0
9     33.0
10    30.0
11    28.0
12    25.0
13    23.0
14    31.0
15    26.0
16    26.0
17    27.0
18    23.0
19    24.0
20    23.0
21    29.0
22    25.0
23    26.0
24    23.0
25    28.0
26    24.0
27    25.0
28    32.0
29    38.0
30    27.0
31    33.0
32    38.0
33    27.0
34    24.0
35    27.0
36    25.0
37    26.0
38    31.0
39    30.0
40    23.0
41    26.0
42    28.0
43    26.0
44    30.0
45    39.0
46    27.0
47    24.0
48    28.0
49    30.0
50     NaN
51    27.0
Name: Age, dtype: float64

In [37]:
#obtener un nuevo dataframe con algunas columnas

df2  = df[['Age','Gender','Height','Wingspan','CWDistance']]
df2

     Age Gender  Height  Wingspan  CWDistance
0   56.0      F   62.00      61.0          79
1   26.0      F   62.00      60.0          70
2   33.0      F   66.00      64.0          85
3   39.0      F   64.00      63.0          87
4   27.0      M   73.00      75.0          72
5   24.0      M   75.00      71.0          81
6   28.0      M   75.00      76.0         107
7   22.0      F   65.00      62.0          98
8   29.0      M   74.00      73.0         106
9   33.0      F   63.00      60.0          65
10  30.0      M   69.50      66.0          96
11  28.0      F   62.75      58.0          79
12  25.0      F   65.00      64.5          92
13  23.0      F   61.50      57.5          66
14  31.0      M   73.00      74.0          72
15  26.0      M   71.00      72.0         115
16  26.0      F   61.50      59.5          90
17  27.0      M   66.00      66.0          74
18  23.0      M   70.00      69.0          64
19  24.0      F   68.00      66.0          85
20  23.0      M   69.00      67.0          66
21  29.0      M   71.00      70.0         101
22  25.0      M   70.00      68.0          82
23  26.0      M   69.00      71.0          63
24  23.0      F   65.00      63.0          67
25  28.0      M   75.00      76.0         111
26  24.0      M   78.40      71.0          92
27  25.0      M   76.00      73.0         107
28  32.0      F   63.00      60.0          75
29  38.0      F   61.50      61.0          78
30  27.0      F   62.00      60.0          72
31  33.0      F   65.30      64.0          91
32  38.0      F   64.00      63.0          86
33  27.0      M   77.00      75.0         100
34  24.0      F   67.80      62.0          98
35  27.0      M   68.00      66.0          74
36  25.0      F   65.00      64.5          92
37  26.0      F   61.50      59.5          90
38  31.0      M   73.00      74.0          72
39  30.0      M   69.50      66.0          96
40  23.0      F   70.40      71.0          66
41  26.0      M   73.50      72.0         115
42  28.0      F   72.50      72.0          81
43  26.0      F   72.00      72.0          92
44  30.0      F   66.00      64.0          85
45  39.0      F   64.00      63.0          87
46  27.0      M   78.00      75.0          72
47  24.0      M   79.50      75.0          82
48  28.0      M   77.80      76.0          99
49  30.0      F   74.60       NaN          71
50   NaN      M   71.00      70.0         101
51  27.0      M     NaN      71.5         103

In [38]:
df2.tail(10)

     Age Gender  Height  Wingspan  CWDistance
42  28.0      F    72.5      72.0          81
43  26.0      F    72.0      72.0          92
44  30.0      F    66.0      64.0          85
45  39.0      F    64.0      63.0          87
46  27.0      M    78.0      75.0          72
47  24.0      M    79.5      75.0          82
48  28.0      M    77.8      76.0          99
49  30.0      F    74.6       NaN          71
50   NaN      M    71.0      70.0         101
51  27.0      M     NaN      71.5         103

In [39]:
#identificar rows
df2.iloc[0]

Age           56.0
Gender           F
Height        62.0
Wingspan      61.0
CWDistance      79
Name: 0, dtype: object

#Estad√≠stica de las variables

Calcular e imprimir estadistica descriptiva

In [40]:
#imprimir estadisticas descriptivas
df2.describe()

             Age     Height   Wingspan  CWDistance
count  51.000000  51.000000  51.000000   52.000000
mean   28.411765  68.971569  67.313725   85.576923
std     5.755611   5.303812   5.624021   14.353173
min    22.000000  61.500000  57.500000   63.000000
25%    25.000000  64.500000  63.000000   72.000000
50%    27.000000  69.000000  66.000000   85.000000
75%    30.000000  73.000000  72.000000   96.500000
max    56.000000  79.500000  76.000000  115.000000